# @generated by cmate 1.1.
# Do not edit this file manually.
# To build all binaries, run: make
# Report issues or contribute at: https://github.com/rock-db/cmate

PROJECT_NAMES := cmate

CMATE_VERSION := 1.1

CC_cmate := clang
CFLAGS_cmate := -Wall -Wextra -std=c99 -DNDEBUG
LDLIBS_cmate :=
LDFLAGS_cmate :=  -O2
SRCDIRS_cmate :=  cmate/src
INCLUDE_DIRS_cmate :=  cmate/include
EXTRA_SOURCES_cmate :=


# Directory settings
OBJDIR := deps/object
BINDIR := bin
# Default GOAL
.DEFAULT_GOAL := all
# List of all binaries (should be set by the generator)
BINARIES := $(addprefix $(BINDIR)/, $(PROJECT_NAMES))
# Ensure bin directory exists
$(BINDIR):
	@mkdir -p $(BINDIR)

define get_sources
    $(foreach dir,$(SRCDIRS_$(1)),\
        $(wildcard $(dir)/*.c) \
        $(wildcard $(dir)/*/*.c) \
        $(wildcard $(dir)/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*/*/*/*/*.c) \
        $(wildcard $(dir)/*/*/*/*/*/*/*/*/*/*.c))
endef

# Auto-detect source files for each binary
define GEN_BINARY_RULES
# ===== $(1) =====
# Variables for $(1)
SRCDIRS_$(1) := $$(SRCDIRS_$(1))
INCLUDE_DIRS_$(1) := $$(INCLUDE_DIRS_$(1))
EXTRA_SOURCES_$(1) := $$(EXTRA_SOURCES_$(1))
LDLIBS_$(1) := $$(LDLIBS_$(1))
LDFLAGS_$(1) := $$(LDFLAGS_$(1))
CFLAGS_$(1) := $$(CFLAGS_$(1))
CC_$(1) := $$(CC_$(1))
SOURCES_$(1) := $$(call get_sources,$(1))
SOURCES_$(1) := $$(SOURCES_$(1)) $$(EXTRA_SOURCES_$(1))
OBJECTS_$(1) := $$(patsubst %.c,$$(OBJDIR)/$(1)/%.o,$$(SOURCES_$(1)))
INCLUDES_$(1) := $$(addprefix -I,$$(INCLUDE_DIRS_$(1)))
CFLAGS_$(1) += $$(INCLUDES_$(1))
# Build rule for $(1)
$$(BINDIR)/$(1): $$(OBJECTS_$(1)) | $$(BINDIR)
	@echo "Linking $(1)"
	@$$(CC_$(1)) $$(LDFLAGS_$(1)) $$(OBJECTS_$(1)) -o $$@ $$(LDLIBS_$(1))
# Object file rule for $(1)
$$(OBJDIR)/$(1)/%.o: %.c
	@mkdir -p $$(dir $$@)
	@echo "Compiling $$<"
	@$$(CC_$(1)) $$(CFLAGS_$(1)) -c $$< -o $$@
endef

# Generate rules for each binary
$(foreach bin,$(PROJECT_NAMES),$(eval $(call GEN_BINARY_RULES,$(bin))))

# Default targets
.PHONY: all clean rebuild help info release
# Main build target
all: $(BINARIES)
	@echo "Build completed: $(BINARIES)"
# Release build target
release: CFLAGS_ALL += -O3 -DNDEBUG -s
release: LDFLAGS_ALL += -s
release: $(BINARIES)
	@echo "Release build completed: $(BINARIES)"
clean:
	@echo "Cleaning up..."
	@rm -rf $(OBJDIR) $(BINDIR) deps
	@echo "Cleanup completed"
rebuild: clean all
# Help
help:
	@echo "Usage: make [target]"
	@echo
	@echo "Available targets:"
	@echo "  all      Build all binaries (default)"
	@echo "  release  Build optimized release version"
	@echo "  clean    Remove generated files"
	@echo "  rebuild  Clean and then build all"
	@echo "  help     Show this help message"
	@echo "  info     Show project information"
	@echo
	@echo "Per-binary targets:"
	@echo "  $(PROJECT_NAMES)"
	@echo
	@echo "This Makefile was generated by cmate $(CMATE_VERSION)."
	@echo "If you encounter any issues or bugs, please open an issue at:"
	@echo "  https://github.com/rock-db/cmate"
# Show project structure
info:
	@echo "Project Structure:"
	@echo "  Source Dirs (per binary):"
	@$(foreach bin,$(PROJECT_NAMES),echo "    $(bin): $(SRCDIRS_$(bin))";)
	@echo "  Include Dirs (per binary):"
	@$(foreach bin,$(PROJECT_NAMES),echo "    $(bin): $(INCLUDE_DIRS_$(bin))";)
	@echo "  Binary outputs: $(BINARIES)"
	@echo "  Project names: $(PROJECT_NAMES)"

