#include <embed_mkfile.h>
#include <gen_makefile.h>
#include <gen_toml.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <term_color.h>
#include <toml.h>
#include <utils.h>

int get_array_len(char **array) {
  int len = 0;
  while (array != NULL && array[len])
    len++;
  return len;
}

char *display_and_collect_libs(char **array, const char *message,
                               const char *base, const char *prefix) {
  char *result = format_string("%s", base);

  int len = get_array_len(array);
  if (len > 0) {
      printf("%s %s", GREEN("=>") ,message);

    for (int i = 0; i < len; i++) {
      char *tmp = result;
      result = format_string("%s %s%s", result, prefix, array[i]);

      if (i != len - 1) {
        printf("%s, ", array[i]);
      } else {
        printf("%s", array[i]);
      }

      free(tmp);
    }
    printf("\n");
  } else {
    INFO("%s (none)\n", message);
    free(result);
    return NULL;
  }

  return result;
}

char *gen_makefile(toml_parsed_t parsed) {

  char *cc = NULL;

  if (parsed.compiler == NULL || strcmp(parsed.compiler, "auto") == 0) {
    char *compiler = auto_detect_compiler();
    if (compiler == NULL) {
      ERROR("The C compiler is not installed!\n");
      return NULL;
    }
    INFO("The C compiler is %s(auto)\n", compiler);
    cc = format_string("CC     := %s", compiler);
  } else {
    char *result = check_depends(parsed);
    if (result == NULL) {
      return NULL;
    }
    cc = format_string("CC     := %s", parsed.compiler);
  }

  INFO("Compile flags: %s\n",
           parsed.cflags ? parsed.cflags : "(none)");

  char *cflags =
      format_string("CFLAGS := %s", parsed.cflags ? parsed.cflags : "");

  char *ldflags = display_and_collect_libs(
      parsed.libraries, "Libraries: ", "LDLIBS	:=", "-l");

  if (ldflags == NULL) {
    ldflags = safe_strdup("LDLIBS	:=");
  }

  char *sources = display_and_collect_libs(
      parsed.srcdirs, "Source directory: ", "SRCDIRS    :=", " ");

  char *includes = display_and_collect_libs(
      parsed.includes, "Include directory: ", "INCLUDE_DIRS :=", " ");

  if (includes == NULL)
    includes = safe_strdup("INCLUDE_DIRS := include");

  char *compile_files = display_and_collect_libs(
      parsed.compile_file, "Extra sources: ", "EXTRA_SOURCES :=", " ");

  if (compile_files == NULL)
    compile_files = safe_strdup("EXTRA_SOURCES :=");

  if (sources == NULL) {
    sources = safe_strdup("SRCDIRS    :=src");
  }

  if (parsed.project_name == NULL) {
    ERROR("Project name not specified in configuration\n");
    free(cc);
    free(sources);
    free(cflags);
    free(ldflags);
    return NULL;
  }

  INFO("Project name: %s\n", parsed.project_name);
  char *project_name =
      format_string("PROJECT_NAME     := %s", parsed.project_name);

  char *copy = malloc(template_Makefile_len + 1);
  if (copy == NULL) {
    ERROR("Failed to allocate memory for Makefile template\n");
    free(cc);
    free(sources);
    free(cflags);
    free(ldflags);
    free(project_name);
    return NULL;
  }

  memcpy(copy, template_Makefile, template_Makefile_len);
  copy[template_Makefile_len] = '\0';

  const char *first =
      "# This Makefile was automatically generated by cate.\n"
      "# You can build the project simply by running make without any "
      "modifications.\n"
      "# If you find any bugs, please submit a PR or open an issue at: "
      "https://github.com/rock-db/cate\n";

  char *prev = format_string("%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n", first,
                             cc, cflags, ldflags, project_name, sources,
                             compile_files, includes, copy);

  printf("[SUCCESS] Makefile generated successfully\n");

  free(cc);
  free(cflags);
  free(project_name);
  free(sources);
  free(compile_files);
  free(includes);
  free(ldflags);

  return prev;
}
